CREATE TABLE IF NOT EXISTS "users" (
"id" INTEGER PRIMARY KEY AUTOINCREMENT,
"email" VARCHAR(200) NOT NULL UNIQUE,
"password" VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS "links" (
"id" INTEGER PRIMARY KEY AUTOINCREMENT,
"source_link" TEXT NOT NULL,
"shortened_link" VARCHAR(12) NOT NULL UNIQUE,
"access_level" INTEGER NOT NULL,
"visit_counter" INTEGER NOT NULL,
"user_created_id" INTEGER
);